services:
  www:
    build: .
    container_name: dispositivos-vtv-php
    volumes:
      - "./src:/var/www/html:z"
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - rede-dispositivos-vtv

  db:
    image: mariadb:latest
    container_name: dispositivos-vtv-mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=America/Sao_Paulo
    networks:
      - rede-dispositivos-vtv
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dispositivos-vtv-phpmyadmin
    restart: always
    ports: 
      - "8081:80"
    environment:
      - PMA_HOST=db
      - TZ=America/Sao_Paulo
    networks:
      - rede-dispositivos-vtv
    depends_on:
      - db

volumes:
  db_data:

networks:
  rede-dispositivos-vtv:
    driver: bridge